name: flutter_final
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  device_preview: ^1.1.0
  introduction_screen: ^3.1.12
  country_picker: ^2.0.18
  pinput: ^3.0.1
  flutter: 
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  dotted_decoration: ^2.0.0
  qr_flutter: ^4.1.0
  intl: ^0.18.1
  table_calendar: ^3.0.8
  image_picker: ^1.0.4
  firebase_core: ^2.19.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.4.0
  provider: ^6.0.5
  flutter_verification_code: ^1.1.7

  

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/

